name: Deploy Terraform to Azure Plan

on:
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.5'
      
      - name: Set TF_VAR_github_token from secret
        run: echo "TF_VAR_github_token=${{ secrets.GH_ACCESS_TOKEN }}" >> $GITHUB_ENV
      - name: Set subsciption ID
        run: echo "TF_VAR_subscription_id=${{ vars.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          TFSTATE_ACCESS_KEY: ${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT_KEY }}
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate" \
            -backend-config="storage_account_name=tfstate28091" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=$TFSTATE_ACCESS_KEY" \
            -backend-config="client_id=$ARM_CLIENT_ID" \
            -backend-config="client_secret=$ARM_CLIENT_SECRET" \
            -backend-config="tenant_id=$ARM_TENANT_ID" \
            -backend-config="subscription_id=$ARM_SUBSCRIPTION_ID"
        working-directory: ./tf

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./tf


