name: Deploy Terraform to Azure Apply

on:
  workflow_dispatch:
    

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          # Create a secret in your repository named AZURE_CREDENTIALS
          # that contains your Azure service principal credentials in JSON format.
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.5'  # Update this to the version of Terraform you prefer
      
      - name: Set TF_VAR_postfix_eu from variable
        run: echo "TF_VAR_postfix_eu=${{ vars.RESOURCE_POSTFIX_EU }}" >> $GITHUB_ENV
      - name: Set TF_VAR_postfix_us from variable
        run: echo "TF_VAR_postfix_us=${{ vars.RESOURCE_POSTFIX_US }}" >> $GITHUB_ENV
      - name: Set TF_VAR_postfix_asia from variable
        run: echo "TF_VAR_postfix_asia=${{ vars.RESOURCE_POSTFIX_ASIA }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=tfstate" -backend-config="storage_account_name=tfstate28091" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate" -backend-config="access_key=${{ secrets.AZURE_TFSTATE_STORAGE_ACCOUNT_KEY }}" -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -backend-config="tenant_id=${{ secrets.AZURE_APPDEPLOY_TENANT_ID}}" -backend-config="subscription_id=${{ secrets.AZURE_APPDEPLOY_SUBSCRIPTION_ID }}"
        working-directory: ./tf

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./tf


