name: Build and deploy PHP app to Azure Web App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip release.zip ./html/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: move the files from the html directory to the root directory
        run: mv html/* .
      
      - name: remove release.zip
        run: rm release.zip
      
      - name: remove html directory
        run: rmdir html

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: 'Deploy to Azure Web App Asia'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp-asia
        with:
          app-name: 'cloudprogrammingproject-3628800-as'
          slot-name: 'Production'
          package: .
      - name: 'Deploy to Azure Web App EU'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp-eu
        with:
          app-name: 'cloudprogrammingproject-3628800-eu'
          slot-name: 'Production'
          package: .
      - name: 'Deploy to Azure Web App US'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp-us
        with:
          app-name: 'cloudprogrammingproject-3628800-us'
          slot-name: 'Production'
          package: .
      
